=== maddie-busig/FINDER-scripts/config_template/finderConverter.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" elementFormDefault="qualified" xsi:schemaLocation="
		http://www.w3.org/2001/XMLSchema
		http://www.w3.org/2001/XMLSchema.xsd">
	<xsd:complexType name="typeOfPattern">
		<xsd:attribute name="patternName" type="xsd:string" use="required"/>
		<xsd:attribute name="inputFile" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:element name="FinderConf">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="systemName" type="xsd:string"/>
				<xsd:element name="moreInstanceDestination" type="xsd:string"/>
				<xsd:element name="pattern" type="typeOfPattern" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== maddie-busig/FINDER-scripts/config_template/finderConverter_tab2ps.xml
<?xml version="1.0" encoding="UTF-8"?>
<FinderConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="finderConverter.xsd">
	<systemName>TAB2PS</systemName>
	<moreInstanceDestination>${FINDER_DIR}/sample/Instance/FINDERInstance/tab2ps</moreInstanceDestination>
	<pattern patternName="Bridge Degenerate" inputFile="${FINDER_DIR}/sample/RawResults/tab2ps.bridge_degenerate.out"/>
	<pattern patternName="Chain of Responsibility" inputFile="${FINDER_DIR}/sample/RawResults/tab2ps.chain.out"/>
	<pattern patternName="Composite" inputFile="${FINDER_DIR}/sample/RawResults/tab2ps.composite.out"/>
	<pattern patternName="Decorator" inputFile="${FINDER_DIR}/sample/RawResults/tab2ps.decorator_degenerate.out"/>
	<pattern patternName="State" inputFile="${FINDER_DIR}/sample/RawResults/tab2ps.state.out"/>
	<pattern patternName="Strategy" inputFile="${FINDER_DIR}/sample/RawResults/tab2ps.strategy.out"/>
	<pattern patternName="Template Method" inputFile="${FINDER_DIR}/sample/RawResults/tab2ps.templatemethod.out"/>
</FinderConf>
